---
layout:     post
title:      Promise
subtitle:  
date:       2022-05-12
author:     
header-img: 
catalog: true
tags:
    - 原生 Javascript 相关
typora-root-url: ..

---

总结：

1. Promise的状态一经改变就不能再改变。
2. .then和.catch都会返回一个新的Promise
3. catch不管被连接到哪里，都能捕获上层未捕捉过的错误
4. 在Promise中，返回任意一个非 promise 的值都会被包裹成 promise 对象，例如return 2会被包装为return Promise.resolve(2)
5. Promise 的 .then 或者 .catch 可以被调用多次, 但如果Promise内部的状态一经改变，并且有了一个值，那么后续每次调用.then或者.catch的时候都会直接拿到该值。
6. .then 或者 .catch 中 return 一个 error 对象并不会抛出错误，所以不会被后续的 .catch 捕获
7. .then 或 .catch 返回的值不能是 promise 本身，否则会造成死循环。
8. .then 或者 .catch 的参数期望是函数，传入非函数则会发生值透传。
9. then方法是能接收两个参数的，第一个是处理成功的函数，第二个是处理失败的函数，再某些时候你可以认为catch是.then第二个参数的简便写法。
10. .finally方法也是返回一个Promise，他在Promise结束的时候，无论结果为resolved还是rejected，都会执行里面的回调函数。
11. finally()方法不管Promise对象最后的状态如何都会执行
12. .finally()方法的回调函数不接受任何的参数，也就是说你在.finally()函数中是没法知道Promise最终的状态是resolved还是rejected的
13. 它最终返回的默认会是一个上一次的Promise对象值，不过如果抛出的是一个异常则返回异常的Promise对象。
14. all和race传入的数组中如果有会抛出异常的异步任务，那么只有最先抛出的错误会被捕获，并且是被then的第二个参数或者后面的catch捕获；但并不会影响数组中其它的异步任务的执行。
15. 紧跟着await后面的语句相当于放到了new Promise中，下一行及之后的语句相当于放在Promise.then中
16. 如果在async函数中抛出了错误，则终止错误结果，不会继续向下执行。